#! /bin/bash
#
# Script to fix timestamps on the RAMS analysis files.
#
# For some reason the HDF5 files are getting dated in the future
# which is subsequently causing the repack script to wait until
# that future date to compress the file.
#
# The header files are getting the correct timestamp. To fix
# this, use touch command to make the timestamp on each
# analysis file match that of its corresponding header
# file.

RamsDir="$1"

for Hfile in $(ls -1 $RamsDir/*-head.txt)
do
  AfilePat=$(echo $Hfile | sed 's/-head.txt/-*.h5/')
  Afiles=$(ls $AfilePat)

  echo "**********************************************************"
  Cmd="touch -r $Hfile $Afiles"
  echo "Running: $Cmd"
  $Cmd
done
