#!/usr/bin/env bash

##############################################################################################
# Script to repack (compress) HDF5 simulation output files

Usage="USAGE: $0 <ramsin_file>"

if [ "$1" == "" ]
then
  echo "ERROR: must supply one argument to script"
  echo ""
  echo $Usage
  exit -1
fi

RamsinFile=$1

GzipLevel=6

# Get the analysis file prefix out of the ramsin file, and use
# this for a pattern match to find the rams output files for this
# simulation.
#
# The first sed filter is to get rid of comments (don't want to pick up a commented
# out value for AFILEPREF)
FilePref=$(sed 's/[!].*//g' $RamsinFile | grep AFILEPREF | sed -e 's/.*=//' -e "s/[', \t]//g")

for RamsFile in ${FilePref}*.h5
do
  echo "***************** $RamsFile ****************************"
  NumGzipDsets=$(h5stat --dset $RamsFile | grep GZIP | sed 's/GZIP filter: //')
  if [ $NumGzipDsets -gt 0 ]
  then
    echo "File is already compressed"
  else
    echo "File needs to be compressed"

    TempFile="${RamsFile}.temp"
    RepackCmd="h5repack -f SHUF -f GZIP=$GzipLevel $RamsFile $TempFile"
    echo "$RepackCmd"
    $RepackCmd

    # only replace the original file if the repack command succeeded
    if [ $? -eq 0 ]
    then
      MvCmd="mv $TempFile $RamsFile"
      echo "$MvCmd"
      $MvCmd
    fi
  fi
done

