#!/usr/bin/env bash

##############################################################################################
# Script to restart a list of RCE simulations

#SimList="RCE_3km_1mom_db_udef RCE_3km_1mom_db_rlongup RCE_3km_2mom_db_udef RCE_3km_2mom_db_rlongup"
SimList="RCE_CHAN_S300"

echo "Restarting RCE simulations: $SimList"
echo

for Sim in $SimList
do
  cd $HOME/Sims/${Sim}
  restart_job run_rams RAMSIN ./RAMS/${Sim}-A-2012-04-30-000000-head.txt
  echo
done
