#!/bin/bash
### Job Name
#PBS -N RceChS300
### Project code
#PBS -A UCSU0054
#PBS -l walltime=12:00:00
#PBS -q economy
### Output and error files
#PBS -e LOG_FILES
#PBS -o LOG_FILES
### Select 42 nodes with 36 CPUs each for a total of 1512 MPI processes
###   This yields an average of 397 columns/core
#PBS -l select=42:ncpus=36:mpiprocs=36
### Send email on abort, begin and end
#PBS -m abe
### Specify mail recipient
#PBS -M stephen.herbener@colostate.edu

### Run the executable
export MPI_TYPE_DEPTH=20
#mpiexec_mpt dplace -s 1 ./rams -f RAMSIN
/glade/u/home/stephenh/Rams/misc/mpich2-1.4.1-install/bin/mpirun -np 1512 ./rams -f RAMSIN
